spring.config.import=classpath:common.properties
spring.application.name=${SERVICE_NAME:payment-initiation}

temporal.address=${TEMPORAL_ADDRESS:localhost:7233}
temporal.namespace=${TEMPORAL_NAMESPACE:default}
