spring.application.name=${SERVICE_NAME:temporal-worker}
server.port=8080

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=never

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%-22logger{22}] trace_id=%X{trace_id:-0} span_id=%X{span_id:-0} uetr=%X{payment.uetr:-} - %msg%n

temporal.address=${TEMPORAL_ADDRESS:localhost:7233}
temporal.namespace=${TEMPORAL_NAMESPACE:default}
temporal.task-queue=payment-processing
