server.port=8080
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=never
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%-22logger{22}] trace_id=%X{trace_id:-0} span_id=%X{span_id:-0} uetr=%X{payment.uetr:-} - %msg%n
spring.application.name=${SERVICE_NAME:network-simulator}
spring.artemis.mode=native
spring.artemis.broker-url=tcp://${SPRING_ARTEMIS_HOST:artemis}:${SPRING_ARTEMIS_PORT:61616}
spring.artemis.user=${SPRING_ARTEMIS_USER:artemis}
spring.artemis.password=${SPRING_ARTEMIS_PASSWORD:artemis}
