spring.config.import=classpath:common.properties
spring.application.name=${SERVICE_NAME:dispatcher}
spring.artemis.mode=native
spring.artemis.broker-url=tcp://${SPRING_ARTEMIS_HOST:artemis}:${SPRING_ARTEMIS_PORT:61616}
spring.artemis.user=${SPRING_ARTEMIS_USER:artemis}
spring.artemis.password=${SPRING_ARTEMIS_PASSWORD:artemis}
